name: When Stones Speak
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73863
title: When Stones Speak
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040301'
    - '#181816'
    - '#272725'
    - '#333837'
    - '#424c50'
  brandStrength: 0.625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
